apiVersion: apps/v1
kind: Deployment
metadata:
  name: primerjalnik-cen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primerjalnik-cen
  template:
    metadata:
      labels:
        app: primerjalnik-cen
    spec:
      containers:
        - image: binem/prpo:latest
          name: primerjalnik-cen
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mel.db.elephantsql.com/uibkmnyz
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: uibkmnyz
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: ycWsntnDpOQ1bD-aC2KWaFwGkTgEcs45
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: primerjalnik-cen
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: primerjalnik-cen