kumuluzee:
  name: primerjalnik-cen
  version: 1.0.0
  env:
    name: dev
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      server-auto-config:
        enabled: false
      mapping: /openapi/ui
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://localhost:5432/primerjalnikCen
      username: postgres
      password: postgres