kumuluzee:
  name: primerjalnik-cen
  version: 1.0.0
  env:
    name: dev
  dev:
    scan-libraries:
      - entitete
      - storitve
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      server-auto-config:
        enabled: false
      mapping: /openapi/ui
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://mel.db.elephantsql.com/uibkmnyz
      username: uibkmnyz
      password: ycWsntnDpOQ1bD-aC2KWaFwGkTgEcs45